### ISSUE TITLE
Text "Account" not responsive

### ISSUE THREAD

**Issue by TheBlueBaronx** [invest-it/linum#47]
On large devices with a lot of pixels (e.g. iPhone XS Max) the text "Account" is cut at the "T".

**Comment by NightmindOfficial** [comment]
Pls add screenshot for those type issues @TheBlueBaronx

**Comment by NightmindOfficial** [comment]
Works on all my devices, so cannot do much here. @TheBlueBaronx make me proud

**Comment by SoTBurst** [comment]
cannot be reproduced. Account is fine on EVERY iPhone including iPhone XS and iPhone XS Max

**Comment by NightmindOfficial** [comment]
New clue: Accessibility controls (iOS), e.g. larger standard fonts, larger app sizes, could mess with our textTheme.

**Comment by TheBlueBaronx** [comment]
This behaviour is also shown with the "Academy" Text on smaller devices

**Comment by NightmindOfficial** [comment]
We'll have to think of a strategy to make some text unaffectable by accessibility features of the system (equivalent to defining decorative elements in ARIA). I will try out my proposed fix to this problem, and then you will need to try it out on the devices affected, okay @VICFR1TZ @TheBlueBaronx ?

**Comment by NightmindOfficial** [comment]
@TheBlueBaronx please check if the error is gone now. The respective branch is called "bug/47"
