### ISSUE TITLE
Typeform not aligned with GH Template

### ISSUE THREAD

**Issue by VICFR1TZ** [invest-it/linum#61]
There are questions/information options missing in the Typeform that are crucial to the process of solving issues quickly.

Check

Remove the text "If a button does not work, this does not apply", as it, in fact, does apply. We need to know what the user expected from clicking the button, nevertheless!

https://api.typeform.com/responses/files/502dbc32453544f78a99986486cd2346c4e40cb06109eb752d0e53e7ca3e1a5c/211002_b_205.jpghttps://zapier-dev-files.s3.amazonaws.com/cli-platform/19059/-a6fRXCz4FKZh0TsW8Omkfjm3OVhK5WR34ZR46vGYKhIWGxCbaNbfbkErzPaTJFSj1t_AjxiUBT815mSRGurEeRuzGQz-_MHKjoMHj9lneXgSw_cuRxBNY6d7iIRI5P58arpJ64I6jriFAc2UZfwbnkj3zXQGzH1ma5IAIveAj8

Mobile

Anroid/

There are some questions missing. I'll text them @Vic

weshouldnotdothis@itisbeingsharedwiththeworld.com

**Comment by NightmindOfficial** [comment]
@VICFR1TZ when will this be finished? I'm asking bc once this is done, I can edit the GH issue templates accordingly.
